[package]
name = "miniproj"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
miniproj-epsg-registry = {version="0.1.0", path="../miniproj-epsg-registry"}

[dependencies]
phf = { version = "~0.11.1", default_features = false}
miniproj-ops= {version="0.1.0", path="../miniproj-ops"}