[package]
name = "miniproj-epsg-registry"
version = "0.5.0"
edition="2021"
license-file = "../LICENSE.md"
authors = ["Flemming St√§bler <fstaebler@geomar.de>", "Valentin Buck <vbuck@geomar.de>"]
description="This crate implements code-generation for miniproj"
readme = "../README.md"
repository = "https://git.geomar.de/flemming-staebler/miniproj/"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version ="0.29", features = ["bundled"] }
phf = { version = "~0.11.1", default_features = false}
phf_codegen = "~0.11.1"
miniproj-ops= {version="0.5.0", path="../miniproj-ops"}