[package]
name = "miniproj-epsg-registry"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version ="0.29", features = ["bundled"] }
phf = { version = "~0.11.1", default_features = false}
phf_codegen = "~0.11.1"
miniproj-ops= {version="0.1.0", path="../miniproj-ops"}